name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15      
    - name: Setup operator-sdk Action
      uses: shivanshs9/setup-k8s-operator-sdk@v1.1.2
      with:
        version: "^0.18.0"
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true   
    - name: Build consul-operator
      run: operator-sdk build consul-operator:test
      working-directory: ./consul-operator
    - name: Test consul-operator
      run: go test -v ./...
      working-directory: ./consul-operator
    - name: Build alarmlogger
      run: go build -v ./...
      working-directory: ./alarmlogger
    - name: Test alarmlogger
      run: go test -v ./...
      working-directory: ./alarmlogger
    - name: Build component-test library
      run: go build -v ./...
      working-directory: ./componenttest-lib
    - name: Test component-test library
      run: go test -v ./...
      working-directory: ./...
